applications:
  app:
    type: php:8.2

    # Rendre var/ writable (cache, logs, asset-mapper)
    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache

    dependencies:
      php:
        composer/composer: "^2"

    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader

      deploy: |
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        php bin/console cache:clear --env=prod
        php bin/console cache:warmup --env=prod

