applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    relationships:
      database: "db:postgresql"

    hooks:
      build: |
        set -e
        # On ajoute --no-scripts pour éviter le crash du cache:clear pendant le build
        composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts

      deploy: |
        set -e
        # On nettoie le cache ici car la DB est enfin disponible
        rm -rf var/cache/prod
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        php bin/console cache:clear
