applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        # On ne fait QUE l'installation. Pas de cache:clear ici.
        composer install --no-dev --prefer-dist --optimize-autoloader

      deploy: |
        set -e
        # On force la suppression du cache hérité du build précédent
        rm -rf var/cache/prod
        
        # On lance les migrations (Upsun injectera la vraie DB Postgres ici)
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        
        # On préchauffe le cache seulement maintenant
        php bin/console cache:clear
