applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: "prod"
        APP_DEBUG: "0"
        # Empêche Symfony Flex de lancer des auto-scripts via composer
        SYMFONY_SKIP_AUTO_SCRIPTS: "1"

    relationships:
      database: "db:postgresql"

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"
          index:
            - index.php

    hooks:
      build: |
        set -e

        # Build = uniquement installation + optimisation autoload (pas de boot Symfony, pas de DB)
        composer install \
          --no-dev \
          --prefer-dist \
          --no-interaction \
          --no-progress \
          --no-scripts \
          --optimize-autoloader

      deploy: |
        set -e

        # Nettoyage cache (safe)
        rm -rf var/cache/prod

        # Construit DATABASE_URL à partir des relations Upsun (DB dispo au deploy)
        export DATABASE_URL="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r \
          '.database[0] | "postgresql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=15&charset=utf8"')"

        # Migrations
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

        # Assets (AssetMapper) — à faire au deploy (boot Symfony OK ici)
        php bin/console asset-mapper:compile --env=prod --no-interaction

        # Cache prod final
        php bin/console cache:clear --env=prod --no-interaction

