applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: "prod"
        APP_DEBUG: "0"
        SYMFONY_SKIP_AUTO_SCRIPTS: "1"

    relationships:
      database: "db:postgresql"

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"
          index:
            - index.php

    hooks:
      build: |
        set -e

        # Installation dépendances (sans scripts)
        composer install \
          --no-dev \
          --prefer-dist \
          --no-interaction \
          --no-progress \
          --no-scripts \
          --optimize-autoloader

        # Compilation AssetMapper AU BUILD (filesystem writable ici)
        php bin/console asset-map:compile --env=prod --no-interaction

      deploy: |
        set -e

        # Nettoyage cache
        rm -rf var/cache/prod

        # DATABASE_URL depuis les relations Upsun
        export DATABASE_URL="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r \
          '.database[0] | "postgresql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=15&charset=utf8"')"

        # Migrations (DB dispo ici)
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

        # Cache final
        php bin/console cache:clear --env=prod --no-interaction

