applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        # Installation propre sans scripts pour éviter les erreurs de DB au build
        composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts

      deploy: |
        set -e
        # Nettoyage du cache pour forcer la relecture des variables Upsun
        rm -rf var/cache/prod
        
        # Exécution des migrations sur PostgreSQL
        # Le paquet config-reader va aider Doctrine à trouver la DATABASE_URL
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        
        # Préchauffage final du cache en production
        php bin/console cache:clear
