applications:
    app:
        type: php:8.2

        variables:
            env:
                APP_ENV: "prod"
                APP_DEBUG: "0"
                SYMFONY_SKIP_AUTO_SCRIPTS: "1"

        relationships:
            database: "db:postgresql"

        mounts:
            "var":
                source: local
                source_path: var

        runtime:
            extensions:
                - pdo_pgsql
                - intl
                - opcache
                - apcu

        dependencies:
            php:
                composer/composer: "^2"

        web:
            locations:
                "/":
                    root: "public"
                    passthru: "/index.php"
                    index:
                        - index.php

        hooks:
            build: |
                set -e

                # La DB Upsun n'est PAS disponible au build.
                # On définit une DATABASE_URL dummy pour éviter que Symfony/Doctrine crash
                # pendant importmap/asset-map/cache warmups éventuels.
                export DATABASE_URL="postgresql://user:pass@127.0.0.1:5432/dummy?serverVersion=15&charset=utf8"

                composer install \
                  --no-dev \
                  --prefer-dist \
                  --no-interaction \
                  --no-progress \
                  --no-scripts \
                  --optimize-autoloader

                # Importmap vendors
                php bin/console importmap:install --env=prod --no-interaction

                # AssetMapper compile
                php bin/console asset-map:compile --env=prod --no-interaction

            deploy: |
                set -e

                # On repart propre sur le cache prod
                rm -rf var/cache/prod

                # La DB est disponible au deploy (relationships runtime OK)
                # On reconstruit une DATABASE_URL réelle depuis PLATFORM_RELATIONSHIPS.
                export DATABASE_URL="$(echo "$PLATFORM_RELATIONSHIPS" | base64 --decode | jq -r \
                  '.database[0] | "postgresql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=15&charset=utf8"')"

                php bin/console doctrine:migrations:sync-metadata-storage --no-interaction
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
                php bin/console cache:clear --env=prod --no-interaction
