applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        # Le build passe car on ignore les scripts
        composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts

      deploy: |
        set -e
        # 1. On nettoie le cache hérité
        rm -rf var/cache/prod
        
        # 2. On extrait manuellement les accès PostgreSQL d'Upsun
        # On décode PLATFORM_RELATIONSHIPS pour créer la DATABASE_URL
        export DATABASE_URL=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0] | "postgresql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=15"')
        
        # 3. On lance les migrations avec la variable forcée
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        
        # 4. On finalise le cache
        php bin/console cache:clear
