applications:
  app:
    type: php:8.2

    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0

    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        # 1. Installation des dépendances sans exécuter les scripts (évite les erreurs de DB)
        composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts
        
        # 2. FIX CSS : Compilation des assets pour la production
        php bin/console asset-mapper:compile

      deploy: |
        set -e
        # 1. Nettoyage du cache de build pour éviter les conflits
        rm -rf var/cache/prod
        
        # 2. Extraction manuelle de la DATABASE_URL depuis les relations Upsun
        export DATABASE_URL=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r '.database[0] | "postgresql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=15"')
        
        # 3. Exécution des migrations sur la base PostgreSQL
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        
        # 4. Préchauffage final du cache
        php bin/console cache:clear
