applications:
  app:
    type: php:8.2

    # Configuration des variables d'environnement globales
    variables:
      env:
        APP_ENV: prod
        APP_DEBUG: 0
        # Simulation d'une DB durant le build pour éviter les erreurs de compilation
        DATABASE_URL: "sqlite:///:memory:"

    # Rendre var/ accessible en écriture pour le cache et les logs
    mounts:
      "var":
        source: local
        source_path: var

    runtime:
      extensions:
        - pdo_pgsql
        - intl
        - opcache
        - apcu

    dependencies:
      php:
        composer/composer: "^2"

    # Lien avec le service de base de données défini dans services.yaml
    relationships:
      database: "db:postgresql"

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"

    hooks:
      build: |
        set -e
        # 1. Installation des dépendances sans les outils de développement
        composer install --no-dev --prefer-dist --optimize-autoloader
        
        # 2. Préchauffage du cache en utilisant la DB simulée
        # Cela permet de figer les routes et les services sans avoir accès à Postgres
        DATABASE_URL="sqlite:///:memory:" php bin/console cache:clear --no-warmup
        DATABASE_URL="sqlite:///:memory:" php bin/console cache:warmup

      deploy: |
        set -e
        # 3. CRUCIAL : Suppression du cache de build
        # On force Symfony à reconstruire son container pour qu'il détecte 
        # enfin la vraie DATABASE_URL (PostgreSQL) fournie par Upsun.
        rm -rf var/cache/prod
        
        # 4. Exécution des migrations sur la vraie base PostgreSQL
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
